### ISSUE TITLE
新版本1.0.0Beta2无法下载

### ISSUE THREAD

**Issue by zhanggongguan** [Houfeng/mditor-desktop#1]
该版本无法下载，目前使用的mac桌面版1.0.0.beta1，在编写的过程中，光标定位不准确，出现跳跃的情况，官网无法下载1.0.0.beta2的dmg安装文件。

**Comment by Houfeng** [comment]
@zhanggongguan 

首先感谢您的反馈，光标定位不准是指「输入法的候选词面板」吗？这个问题是由 WebKit 的一个 Bug 导致，已向上游反馈 issue，同时在 Beta2 中通过变通的方法「尽可能的规避」了这个问题。

刚刚试了一下，是能下载的，http://mditor.com/，您下载失败时是何错误？
