### ISSUE TITLE
导出pdf或者doc的时候图片没法显示

### ISSUE THREAD

**Issue by junfengtang** [Houfeng/mditor-desktop#2]
RT

**Comment by Houfeng** [comment]
@junfengtang 

感谢您的反馈，能否提供下以下信息：
1. 系统版本
2. Mditor 版本
3. 重现步骤

重现问题后，将及时修复。

**Comment by junfengtang** [comment]
MAC 10.11.6
版本 1.0.0Beta2 (1.0.0Beta2)
就是导出pdf或者doc后，打开后里面显示不了图片

**Comment by Houfeng** [comment]
@junfengtang 
已重现些问题，下周将会发布一个版本，一并修复这个问题。

**Comment by Houfeng** [comment]
@junfengtang 
已修复此问题，请下载最新版 [http://mditor.com](http://mditor.com)

**Comment by junfengtang** [comment]
@Houfeng Good job!感觉这个还不错！mac上听实用的

**Comment by Houfeng** [comment]
@junfengtang 
多谢
